### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = './run_archive/connect4/run0001/models/version0001.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by SCoulY** [AppliedDataSciencePartners/DeepReinforcementLearning#11]
I can not play matches between versions:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-1e9b80eae750> in <module>()
      4 
      5 env = Game()
----> 6 playMatchesBetweenVersions(env, 1, 1, 1, 10, lg.logger_tourney, 0)

~/DeepReinForcementLearning/DeepReinforcementLearning/funcs.py in playMatchesBetweenVersions(env, run_version, player1version, player2version, EPISODES, logger, turns_until_tau0, goes_first)
     19 
     20         if player1version > 0:
---> 21             player1_network = player1_NN.read(env.name, run_version, player1version)
     22             player1_NN.model.set_weights(player1_network.get_weights())
     23         player1 = Agent('player1', env.state_size, env.action_size, config.MCTS_SIMS, config.CPUCT, player1_NN)

~/DeepReinForcementLearning/DeepReinforcementLearning/model.py in read(self, game, run_number, version)
     37 
     38         def read(self, game, run_number, version):
---> 39                 return load_model( run_archive_folder + game + '/run' + str(run_number).zfill(4) + "/models/version" + "{0:0>4}".format(version) + '.h5', custom_objects={'softmax_cross_entropy_with_logits': softmax_cross_entropy_with_logits})
     40 
     41         def printWeightAverages(self):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py in load_model(filepath, custom_objects, compile)
    235             return custom_objects[obj]
    236         return obj
--> 237     with h5py.File(filepath, mode='r') as f:
    238         # instantiate model
    239         model_config = f.attrs.get('model_config')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = './run_archive/connect4/run0001/models/version0001.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by ezrahn** [comment]
Once you have a set of training models, copy directories under ~run/* to ~run_archive/connect4/run001/*, then you should be able to play.

I added a little script in my fork (play_game.py) for a better interface of human playing against AI.

There are bugs in the initial game model, including 
- Being able to place a coin hanging in the air, while the original connect 4 is played on a vertical board where the coins fall due to gravity. 
- Human player can place a coin that is already filled, e.g. no input validation yet.

Will try to fix these and contribute back.

**Comment by ezrahn** [comment]
I just added the validation for human player moves, and a better interface for human to interact with the game. Once the model is trained, copy directories under ~run/* to ~run_archive/connect4/run001/*.

To play the game, run: python play_game.py
See: https://github.com/ezrahn/DeepReinforcementLearning

**Comment by SCoulY** [comment]
Sorry for the late reply.
I do fix the bug through your instruction, but i found my MacBook Pro can not afford this GPU-hungry program.
Thanks anyway.

**Comment by FireFoxtrott** [comment]
Hello,
i have the same problem as SCoulY with 

OSError: Unable to open file (unable to open file: name = './run_archive/connect4/run0001/models/version0001.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

What exactly is the version0001.h5 file? 

Thanks for help

**Comment by DiyuanLu** [comment]
My problem is I 
model.save_model("model"). It kind shows it's in .h5 format with actually without the extension.
When I just write loaded_model = load_model('model'), everything works.
