### ISSUE TITLE
unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by slothkins** [AppliedDataSciencePartners/DeepReinforcementLearning#12]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\ProgramData\Anaconda2\envs\keras36\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     51     try:
---> 52         return getattr(obj, method)(*args, **kwds)
     53 

AttributeError: 'NoneType' object has no attribute 'round'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-4-860091d9e167> in <module>()
      4 
      5 env = Game()
----> 6 playMatchesBetweenVersions(env, 1, -1, 1, 10, lg.logger_tourney, 0)

~\Documents\GitHub\DeepReinforcementLearning-master\funcs.py in playMatchesBetweenVersions(env, run_version, player1version, player2version, EPISODES, logger, turns_until_tau0, goes_first)
     33         player2 = Agent('player2', env.state_size, env.action_size, config.MCTS_SIMS, config.CPUCT, player2_NN)
     34 
---> 35     scores, memory, points, sp_scores = playMatches(player1, player2, EPISODES, logger, turns_until_tau0, None, goes_first)
     36 
     37     return (scores, memory, points, sp_scores)

~\Documents\GitHub\DeepReinforcementLearning-master\funcs.py in playMatches(player1, player2, EPISODES, logger, turns_until_tau0, memory, goes_first)
     96             for r in range(env.grid_shape[0]):
     97                 logger.info(['----' if x == 0 else '{0:.2f}'.format(np.round(x,2)) for x in pi[env.grid_shape[1]*r : (env.grid_shape[1]*r + env.grid_shape[1])]])
---> 98             logger.info('MCTS perceived value for %s: %f', state.pieces[str(state.playerTurn)] ,np.round(MCTS_value,2))
     99             logger.info('NN perceived value for %s: %f', state.pieces[str(state.playerTurn)] ,np.round(NN_value,2))
    100             logger.info('====================')

C:\ProgramData\Anaconda2\envs\keras36\lib\site-packages\numpy\core\fromnumeric.py in round_(a, decimals, out)
   2849 
   2850     """
-> 2851     return around(a, decimals=decimals, out=out)
   2852 
   2853 

C:\ProgramData\Anaconda2\envs\keras36\lib\site-packages\numpy\core\fromnumeric.py in around(a, decimals, out)
   2835 
   2836     """
-> 2837     return _wrapfunc(a, 'round', decimals=decimals, out=out)
   2838 
   2839 

C:\ProgramData\Anaconda2\envs\keras36\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     60     # a downstream library like 'pandas'.
     61     except (AttributeError, TypeError):
---> 62         return _wrapit(obj, method, *args, **kwds)
     63 
     64 

C:\ProgramData\Anaconda2\envs\keras36\lib\site-packages\numpy\core\fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     40     except AttributeError:
     41         wrap = None
---> 42     result = getattr(asarray(obj), method)(*args, **kwds)
     43     if wrap:
     44         if not isinstance(result, mu.ndarray):

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Hi. Running this in python 3.6.

Managed to get past lots of errors so far with the help of this thread but I've got no idea on this.

Can anybody help, please?

**Comment by davidADSP** [comment]
Latest version is Python 3 compatible. Make sure you've got a trained version in the run folder, that you can play against (i.e. there should be a version0001 in the run/models folder.

**Comment by aletote** [comment]
After solving the error "only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices" with the suggested before:
in agent.py change line 26 to
action = int(input('Enter your chosen action: '))

I'm now getting "unsupported operand type(s) for *: 'NoneType' and 'float'" when I type any number. Trained version is in the run folder and I'm using Python3. Can you help please?

Btw, I'm using nodges and crosses game.py uploaded by someone after training it for 8 hours.
