### ISSUE TITLE
Missing requirements / pipfile

### ISSUE THREAD

**Issue by iandanforth** [AppliedDataSciencePartners/DeepReinforcementLearning#2]
Running this example has the following prerequisites

[Graphviz](https://graphviz.gitlab.io/download/)

Example install for Ubuntu 16.04
```
sudo apt install graphviz
```
Python 2.7

It also requires the following packages be installed and working. Here is an example Pipfile which can be used with [pipenv](http://pipenv.readthedocs.io/en/latest/) to get running 

Copy to a file name 'Pipfile' in dir `DeepReinforcementLearning/`
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]


[packages]

jupyter = "*"
numpy = "*"
Keras = "*"
tensorflow = "*"
matplotlib = "*"
pydot = "*"

[requires]
python_version = "2.7"
```

Then install the required modules from that Pipfile using pipenv and run Jupyter
```
pip install --user pipenv
cd DeepReinforcementLearning/
pipenv install
pipenv shell 
jupyter notebook
```

Other steps may be required on other systems, this was the minimum required to get running on my Ubuntu 16.04 machine.

**Comment by threedliteguy** [comment]
After following these instructions (I have python 3) and installing a couple additional missing libraries in the pipenv shell, I get: 
.local/share/virtualenvs/DeepReinforcementLearning-VD1GuYsO/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py
AttributeError: 'int' object attribute '__doc__' is read-only

**Comment by iandanforth** [comment]
@threedliteguy Did you find a work around? Uninstalling enum and installing a variant keeps coming up in my searches, see https://stackoverflow.com/questions/45796177/bazel-tensorflow-inception-v3-retraining-attributeerror-int-object-attrib

**Comment by gbishop** [comment]
I've got it running with the following Pipfile. But I'm still getting errors after LONGGG run times. Is this known to be Python2.7? It looks compatible with 3...

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]

jupyter = "*"
numpy = "*"
keras = "*"
tensorflow = "*"
pydot = "*"
jsonschema = "*"
enum = "*"
"pathlib2" = "*"
"enum34" = "*"
mock = "*"
np-utils = "*"
"backports.functools-lru-cache" = "*"
matplotlib = "*"
"h5py" = "*"
nbconvert = "*"
"html5lib" = "*"


[requires]

python_version = "2.7"
```

**Comment by threedliteguy** [comment]
I was able to get it to train with @gbishop 's Pipfile and pip installed in the shell all the items listed, except I used tensorflow-gpu (which is now 1.5, hence a few deprecation warnings). Interrupted it after 3 iterations of 30 games each.  However when using the models, got: 
File not found ./run_archive/connect4/run0001/models/version0001.h5

**Comment by davidADSP** [comment]
Before training any models, it fills the memory with game data - so you'll need to leave it running until the memory size reaches the MEMORY_SIZE specified in the config.py file. The reason for having a large memory size is that it needs to ensure it's not sampling from the same game when it draws its mini-batch of 256 positions to train on.

The str(iteration) bug is now fixed on master

**Comment by threedliteguy** [comment]
The losses dropped initially but then stayed at the same level for most of the remaining 50, in the final graph.

**Comment by davidADSP** [comment]
Latest version contains requirements.txt file
