### ISSUE TITLE
Not working for Python 3

### ISSUE THREAD

**Issue by Naereen** [AppliedDataSciencePartners/DeepReinforcementLearning#4]
For some reasons (#1) and because of the use of `reload`(now `importlib.reload`), the notebook don't work for Python 3.

**Comment by amansidhant** [comment]
From Claude Coulombe's comment on the original post:
Change xrange(…) by range(…) in game.py, funcs.py, model.py, agent.py, … So find and replace in all .py files
Comment the logger instruction below in the MCTS.py
# lg.logger_mcts.info(‘action: %d (%d)… N = %d, P = %f, nu = %f, adjP = %f, W = %f, Q = %f, U = %f, Q+U = %f’
 # , action, action % 7, edge.stats[‘N’], round(edge.stats[‘P’],6), round(nu[idx],6), ((1-epsilon) * edge.stats[‘P’] + epsilon * nu[idx] )
 # , round(edge.stats[‘W’],6), round(Q,6), round(U,6), round(Q+U,6))

**Comment by machinelearningblr** [comment]
You can change round to np.round as well. I got it working on Python 3 + Windows 10 (added this line os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/' to fix graphviz-pydot error)

**Comment by Naereen** [comment]
@machinelearningblr Adding Windows-specific and version-specific code can only be a local fix, it shouldn't be added to the codebase (IMO)

**Comment by jdori** [comment]
I have a fork working on my local machine with at least Python 3.6.3 and 3.6.4: https://github.com/jdori/DeepReinforcementLearning

I'd be happy to clean up some if anyone thinks I should submit a PR

**Comment by Naereen** [comment]
@jdori Great! Wait until someone from @AppliedDataScience replies here, it's useless to clean up and send a PR if they won't merge it.

**Comment by ChameleonRed** [comment]
It will be nice to release Windows 10/Python 3.6 version since many people use such configuration. Personally I can use Linux but currently does not have machine with Linux. It could be great example of good project from @AppliedDataScience.

I am very good coder so can fix it.

**Comment by Naereen** [comment]
@ChameleonRed if "so can fix it": if you submit a PR, and someone can merge it, it would help.

**Comment by archcra** [comment]
I am using docker image: jupyter tensorflow vertion(https://github.com/jupyter/docker-stacks/tree/master/tensorflow-notebook), but this image only support python3. So, I am eagerly looking forward to the python 3 supported solution. Thank you very much!
--
May the force be with you.

**Comment by davidADSP** [comment]
Latest version is now Python3 compatible

**Comment by Naereen** [comment]
Great!
