### ISSUE TITLE
Comparison with AlphaZero results

### ISSUE THREAD

**Issue by ericvrp** [AppliedDataSciencePartners/DeepReinforcementLearning#6]
Thank you very much for this great source of information!!

Has any experiments been done to see if results comparable with DeepMind's chess and shogi publications can be achived. i.e. is this implementation indeed feature complete and as written in the Nature papers?

**Comment by davidADSP** [comment]
This version is not feature complete (for example, the deep NN is trained continuously) but still captures most of the key ingredients of the AlphaZero paper.
