### ISSUE TITLE
name 'reload' is not defined

### ISSUE THREAD

**Issue by dukeng** [AppliedDataSciencePartners/DeepReinforcementLearning#7]
Hi. I cloned your repo and got it to work until i ran "2. Now run this block to start the learning process" in run.ipynb and I got this error:

NameError                                 Traceback (most recent call last)
<ipython-input-2-d4b5dcf02dd7> in <module>()
     53 
     54     iteration += 1
---> 55     reload(lg)
     56     reload(config)
     57 

NameError: name 'reload' is not defined

I'm not sure what to go from here as I'm not familiar with the codebase. I would really appreciate if you could give some guidance here. Thanks!

**Comment by mfornet** [comment]
`reload` is now (in python 3.x) under imporlib. If you are using python3.x use:
`from importlib import reload`

**Comment by dukeng** [comment]
Thanks. I had to disable the log.logger in MCTS but it's working now!

**Comment by davidADSP** [comment]
Latest version is now Python3 compatible, with `from importlib import reload` added
