### ISSUE TITLE
Issue with concatenation of string and integer while pickling

### ISSUE THREAD

**Issue by ezrahn** [AppliedDataSciencePartners/DeepReinforcementLearning#8]
Very minor issue with the code, main.py:103:

pickle.dump( memory, open( run_folder + "memory/memory" + iteration + ".p", "wb" ) )

should have probably been:

pickle.dump( memory, open( run_folder + "memory/memory" + str(iteration) + ".p", "wb" ) )

**Comment by davidADSP** [comment]
fixed
